import {BluetoothSdk} from "./_private/BluetoothSdkModule"

export default BluetoothSdk

export {
  DeviceModels,
  createDisconnectedGlassesStatus,
  isBusyGlassesConnectionStatus,
  isConnectedGlassesConnectionStatus,
  isConnectedWifiStatus,
  isEnabledHotspotStatus,
  isReadyGlassesConnectionStatus,
} from "./BluetoothSdk.types"

export type {
  AudioConnectedEvent,
  AudioDisconnectedEvent,
  AudioPairingNeededEvent,
  BatteryStatusEvent,
  BluetoothSdkEvent,
  BluetoothSdkEventListener,
  BluetoothSdkEventMap,
  BluetoothSdkEventName,
  BluetoothSdkPublicModule as BluetoothSdkModule,
  BluetoothSdkSubscription,
  ButtonPhotoSize,
  ButtonPressEvent,
  CameraFov,
  CompatibleGlassesSearchStopEvent,
  ConnectOptions,
  ConnectedGlassesConnectionStatus,
  ConnectedWifiStatus,
  Device,
  DeviceModel,
  EnabledHotspotStatus,
  GalleryMode,
  GalleryStatusEvent,
  GlassesConnectionStatus,
  GlassesMediaVolumeGetResult,
  GlassesMediaVolumeSetResult,
  GlassesNotReadyEvent,
  HeadUpEvent,
  HotspotErrorEvent,
  HotspotStatus,
  HotspotStatusChangeEvent,
  KeepAliveAckEvent,
  LocalTranscriptionEvent,
  LogEvent,
  MicLc3Event,
  MicMode,
  MicPcmEvent,
  MicPreference,
  PairFailureEvent,
  PhotoCompression,
  PhotoResponseEvent,
  PhotoSize,
  PublicBluetoothStatus as BluetoothStatus,
  PublicGlassesStatus as GlassesStatus,
  RgbLedAction,
  RgbLedColor,
  RgbLedControlResponseEvent,
  ScanModelOptions,
  ScanOptions,
  ScanResultsCallback,
  StreamAudioConfig,
  StreamKeepAliveRequest,
  StreamStartRequest,
  StreamStatusEvent,
  StreamStatusLifecycleState,
  StreamStatusReconnectState,
  StreamStatusState,
  StreamVideoConfig,
  SwipeVolumeStatusEvent,
  SwitchStatusEvent,
  TouchEvent,
  VadStatusEvent,
  WifiSearchResult,
  WifiStatus,
  WifiStatusChangeEvent,
} from "./BluetoothSdk.types"
