name: Build AugmentOS Projects

on:
  push:
    branches: [ main, feature/ci ]
  pull_request:
    branches: [ main, feature/ci ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './augmentos_manager/package-lock.json'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build augmentos_core
      working-directory: ./augmentos_core
      run: |
        chmod +x ./gradlew
        ./gradlew build

    - name: Install npm dependencies and build augmentos_manager
      working-directory: ./augmentos_manager
      run: |
        npm install
        npm run build

    - name: Build augmentos_manager Android
      working-directory: ./augmentos_manager/android
      run: |
        chmod +x ./gradlew
        ./gradlew build 